source xxliquidutility.mel;

global proc AEliquidSubdivisionSurfaceShape(string $node)
{
  liqPushIdent();
  liqAElog("AEliquidSubdivisionSurfaceShape("+$node+")");


  editorTemplate -beginLayout "Liquid" -collapse true;

    editorTemplate  -beginLayout "Rendering" -collapse false;

      editorTemplate -label "Maya Crease Hardness" -addControl "liqSubdivMayaCrease";

    editorTemplate -endLayout;

  editorTemplate -endLayout;

  liqPopIdent();
}
