#ifndef _SHADER_PARAMETER_TYPE_
#define _SHADER_PARAMETER_TYPE_

typedef enum {
	SHADER_TYPE_UNKNOWN,
	SHADER_TYPE_POINT,
	SHADER_TYPE_COLOR,
	SHADER_TYPE_SCALAR,
	SHADER_TYPE_STRING,
	/* The following types are primarily used for shaders */
	SHADER_TYPE_SURFACE,
	SHADER_TYPE_LIGHT,
	SHADER_TYPE_DISPLACEMENT,
	SHADER_TYPE_VOLUME,           // 8
	SHADER_TYPE_TRANSFORMATION,
	SHADER_TYPE_IMAGER,
	/* The following are variable types added since RISpec 3.1 */
	SHADER_TYPE_VECTOR,
	SHADER_TYPE_NORMAL,
	SHADER_TYPE_MATRIX,
	/* The following is for co-shading */
	SHADER_TYPE_SHADER
} SHADER_TYPE;


typedef enum {
	SHADER_DETAIL_UNKNOWN,
	SHADER_DETAIL_VARYING,
	SHADER_DETAIL_UNIFORM
} SHADER_DETAIL;

#endif//_SHADER_PARAMETER_TYPE_